creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 7D90DA852981F9E91D82135D2EEDDEE013523CAA
#    ,ANOTHER_FALSE_KEY_HERE
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 7D90DA852981F9E91D82135D2EEDDEE013523CAA
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_FALSE_KEY_HERE
